[build]
  base    = "src/vanilla"
  command = "yarn install --frozen-lockfile && LIFF_ID='2007934501-Q15J9pAG' yarn build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  LIFF_ID = "2007934501-Q15J9pAG"
